export default {
  products: [
    {
      productId: 1,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d1.jpg',
      price: 30,
      brand: 'Nike',
      rating: 4.0,
      numberOfReviews: 22,
    },
    {
      productId: 2,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d2.jpg',
      price: 80,
      brand: 'Nike',
      rating: 5.0,
      numberOfReviews: 8,
    },
    {
      productId: 3,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d3.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numberOfReviews: 10,
    },
    {
      productId: 4,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d4.jpg',
      price: 50,
      brand: 'Nike',
      rating: 4.3,
      numberOfReviews: 17,
    },
    {
      productId: 5,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d5.jpg',
      price: 60,
      brand: 'Nike',
      rating: 4.5,
      numberOfReviews: 12,
    },
    {
      productId: 6,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d6.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.7,
      numberOfReviews: 20,
    },
    {
      productId: 7,
      name: 'Slim Shirt',
      category: 'shirts',
      image: '/images/d7.jpg',
      price: 40,
      brand: 'Nike',
      rating: 4.0,
      numberOfReviews: 10,
    },
  ],
};
